import type { Market } from '../lib/types';

/** Build a Market for tests with sensible defaults. */
export function makeMarket(over: Partial<Market> = {}): Market {
  return {
    id: 'x',
    source: 'polymarket',
    title: 'Title',
    marketUrl: 'https://polymarket.com/event/x',
    image: '',
    category: 'Politics',
    description: '',
    favored: 'Yes',
    oddsPct: 50,
    alt: null,
    divergence: null,
    movement24h: 0,
    movement7d: null,
    oddsHistory: [],
    volume: 1000,
    volume24h: 100,
    liquidity: 100,
    openInterest: 0,
    comments: 0,
    score: 1,
    startDate: null,
    endDate: '2026-12-01T00:00:00Z',
    status: 'active',
    hook: 'hook',
    analysis: 'analysis',
    take: '',
    marketRead: '',
    crowdVsCoverage: '',
    synthesis: null,
    sources: [],
    grounded: false,
    generatedAt: '2026-06-15T00:00:00Z',
    updatedAt: '2026-06-15T00:00:00Z',
    resolvedOutcome: null,
    calledCorrectly: null,
    resolvedAt: null,
    ...over,
  };
}
